---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
        - ["private_network", {ip: "192.168.56.42"}]
        
suites:
  - name: default
    run_list:
      - recipe[chef-cd-workshop::default]
    attributes:
