name             'chef-cd-workshop'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures chef-cd-workshop'
long_description 'Installs/Configures chef-cd-workshop'
version          '0.1.0'

depends 'yum'
depends 'jenkins'
depends 'chef-dk'
depends 'docker'
